#!/bin/bash
set -euo pipefail

OUT_DIR="${1:-}"
ROOT_SOLUTION="${2:-none}"
CONFIG_FILE="$OUT_DIR/.config"

if [ -z "$OUT_DIR" ] || [ ! -f "$CONFIG_FILE" ]; then
	echo "Usage: $0 <out_dir> [root_solution]" >&2
	exit 1
fi

echo "[+] Applying Kali NetHunter kernel configs"

# PixelOS usb_f_gsi.ko provides RNDIS and owns rndis_add_hdr.
scripts/config --file "$CONFIG_FILE" \
	-e CONFIG_USB_CONFIGFS \
	-e CONFIG_USB_CONFIGFS_F_HID \
	-e CONFIG_USB_F_HID \
	-d CONFIG_USB_CONFIGFS_RNDIS \
	-d CONFIG_USB_F_RNDIS \
	-e CONFIG_USB_CONFIGFS_EEM \
	-e CONFIG_USB_CONFIGFS_ECM \
	-m CONFIG_USB_NET_CDC_SUBSET \
	-m CONFIG_USB_NET_RNDIS_HOST \
	-e CONFIG_WIRELESS \
	-e CONFIG_WIRELESS_EXT \
	-e CONFIG_WEXT_CORE \
	-e CONFIG_WEXT_PROC \
	-e CONFIG_WEXT_PRIV \
	-m CONFIG_CFG80211 \
	-d CONFIG_CFG80211_WEXT \
	-m CONFIG_MAC80211 \
	-e CONFIG_WLAN_VENDOR_ATH \
	-e CONFIG_WLAN_VENDOR_RALINK \
	-e CONFIG_WLAN_VENDOR_REALTEK \
	-m CONFIG_RTL8XXXU \
	-e CONFIG_RTL8XXXU_UNTESTED \
	-m CONFIG_RT2X00 \
	-m CONFIG_RT2800USB \
	-e CONFIG_RT2800USB_RT3573 \
	-e CONFIG_RT2800USB_RT53XX \
	-e CONFIG_RT2800USB_RT55XX \
	-e CONFIG_RT2800USB_UNKNOWN \
	-m CONFIG_RT2800_LIB \
	-m CONFIG_RT2X00_LIB_USB \
	-m CONFIG_RT2X00_LIB \
	-e CONFIG_RT2X00_LIB_FIRMWARE \
	-m CONFIG_ATH_COMMON \
	-m CONFIG_ATH9K_HW \
	-m CONFIG_ATH9K_COMMON \
	-m CONFIG_ATH9K_HTC \
	-e CONFIG_ATH9K_HTC_DEBUGFS \
	-m CONFIG_BT_HCIBTUSB \
	-m CONFIG_USB_SERIAL \
	-e CONFIG_USB_SERIAL_GENERIC \
	-m CONFIG_USB_SERIAL_CH341 \
	-m CONFIG_USB_SERIAL_CP210X \
	-m CONFIG_USB_SERIAL_FTDI_SIO \
	-m CONFIG_USB_SERIAL_PL2303 \
	-m CONFIG_USB_SERIAL_OPTION \
	-m CONFIG_CIFS \
	-m CONFIG_NFS_FS \
	-e CONFIG_NFS_V3 \
	-e CONFIG_NFS_V4 \
	-m CONFIG_LOCKD \
	-m CONFIG_SUNRPC \
	-e CONFIG_BRIDGE \
	-e CONFIG_TUN \
	-e CONFIG_VETH \
	-e CONFIG_DUMMY \
	-e CONFIG_PACKET \
	-m CONFIG_PACKET_DIAG \
	-e CONFIG_USB_STORAGE \
	-e CONFIG_USB_CONFIGFS_MASS_STORAGE \
	-m CONFIG_USB_ACM

if [ "$ROOT_SOLUTION" = "ksu-next" ]; then
	scripts/config --file "$CONFIG_FILE" -e CONFIG_KSU
fi

echo "[+] NetHunter configs applied for root=$ROOT_SOLUTION"
